# Farmacia_Cuxibamba/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from Farmacia import views

urlpatterns = [
    # Otras rutas...
    path('admin/', admin.site.urls),
    path('admin/crud/', views.crud_view, name='crud'),
    path('registrar_usuario/', views.registrar_usuario, name='registrar_usuario'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home_view, name='home'),
    path('success/', views.success, name='success'),
    path('', views.root, name='root'),
    path('cliente/', views.cliente, name='cliente'),
    path('empleado/', views.empleado, name='empleado'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/profile/', views.profile, name='profile'),
    path('medicamentos/', views.medicamento_list, name='medicamento_list'),
    path('medicamentos/create/', views.medicamento_create, name='medicamento_create'),
    path('medicamentos/<int:pk>/update/', views.medicamento_update, name='medicamento_update'),
    path('medicamentos/<int:pk>/delete/', views.medicamento_delete, name='medicamento_delete'),
    path('clientes/', views.cliente_list, name='cliente_list'),
    path('clientes/create/', views.cliente_create, name='cliente_create'),
    path('clientes/<int:pk>/update/', views.cliente_update, name='cliente_update'),
    path('clientes/<int:pk>/delete/', views.cliente_delete, name='cliente_delete'),
    path('management_system/', views.management_system_view, name='management_system'),
    path('direcciones/', views.direccion_list, name='direccion_list'),
    path('direcciones/create/', views.direccion_create, name='direccion_create'),
    path('direcciones/<int:pk>/update/', views.direccion_update, name='direccion_update'),
    path('direcciones/<int:pk>/delete/', views.direccion_delete, name='direccion_delete'),
    path('farmacias/', views.farmacia_list, name='farmacia_list'),
    path('farmacias/create/', views.farmacia_create, name='farmacia_create'),
    path('farmacias/<int:pk>/update/', views.farmacia_update, name='farmacia_update'),
    path('farmacias/<int:pk>/delete/', views.farmacia_delete, name='farmacia_delete'),
    path('sucursales/', views.sucursal_list, name='sucursal_list'),
    path('sucursales/create/', views.sucursal_create, name='sucursal_create'),
    path('sucursales/<int:pk>/update/', views.sucursal_update, name='sucursal_update'),
    path('sucursales/<int:pk>/delete/', views.sucursal_delete, name='sucursal_delete'),
    path('administrativos/', views.administrativo_list, name='administrativo_list'),
    path('administrativos/create/', views.administrativo_create, name='administrativo_create'),
    path('administrativos/<int:pk>/update/', views.administrativo_update, name='administrativo_update'),
    path('administrativos/<int:pk>/delete/', views.administrativo_delete, name='administrativo_delete'),
    path('ventas/', views.venta_list, name='venta_list'),
    path('ventas/create/', views.venta_create, name='venta_create'),
    path('ventas/<int:pk>/update/', views.venta_update, name='venta_update'),
    path('ventas/<int:pk>/delete/', views.venta_delete, name='venta_delete'),
    path('inventarios/', views.inventario_list, name='inventario_list'),
    path('inventarios/create/', views.inventario_create, name='inventario_create'),
    path('inventarios/<int:pk>/update/', views.inventario_update, name='inventario_update'),
    path('inventarios/<int:pk>/delete/', views.inventario_delete, name='inventario_delete'),
    path('transferencias/', views.transferencia_list, name='transferencia_list'),
    path('transferencias/create/', views.transferencia_create, name='transferencia_create'),
    path('transferencias/<int:pk>/update/', views.transferencia_update, name='transferencia_update'),
    path('transferencias/<int:pk>/delete/', views.transferencia_delete, name='transferencia_delete'),
path('detalles_venta/', views.detalle_venta_list, name='detalle_venta_list'),
    path('detalles_venta/create/', views.detalle_venta_create, name='detalle_venta_create'),
    path('detalles_venta/<int:pk>/update/', views.detalle_venta_update, name='detalle_venta_update'),
    path('detalles_venta/<int:pk>/delete/', views.detalle_venta_delete, name='detalle_venta_delete'),
]