# Generated by Django 5.1.5 on 2025-01-31 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_alter_usuario_nombre_alter_usuario_teléfono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferenciaDeMedicamentos',
            new_name='TransferenciaDeMedicamento',
        ),
    ]
